# VacationPy
----

#### Note
* Instructions have been included for each segment. You do not have to follow them exactly, but they are included to help you think through the steps.

In [14]:
# Dependencies and Setup
import matplotlib.pyplot as plt
import pandas as pd
import numpy as np
import requests
import gmaps
import os
from pprint import pprint

# Import API key
from api_keys import g_key

### Store Part I results into DataFrame
* Load the csv exported in Part I to a DataFrame

In [15]:
# Output File (CSV)
output_data_file = "../output_data/cities.csv"

# read file
df = pd.read_csv(output_data_file)

# print data frame
df

,City,Country,Date,Latitude,Longitude,Cloudiness,Humidity,Max Temperature,Wind Speed
0,Busselton,AU,2020-03-18 18:57:15,-33.65,115.33,84,67,55.99,8.03
1,Port Alfred,ZA,2020-03-18 18:57:15,-33.59,26.89,26,87,68.00,1.99
2,Pacific Grove,US,2020-03-18 18:52:17,36.62,-121.92,90,58,57.20,10.29
3,Wanaka,NZ,2020-03-18 18:57:15,-44.70,169.15,21,74,48.16,10.76
4,Havøysund,NO,2020-03-18 18:57:15,71.00,24.66,90,92,26.60,23.04
...,...,...,...,...,...,...,...,...,...
563,Bāgeshwar,IN,2020-03-18 19:01:01,29.85,79.77,4,50,40.78,7.27
564,Galle,LK,2020-03-18 19:01:01,6.04,80.22,68,80,81.10,13.27
565,Altay,CN,2020-03-18 19:01:01,47.87,88.12,94,78,23.32,2.55
566,Yenagoa,NG,2020-03-18 19:01:01,4.92,6.26,50,88,79.84,7.09
567,Santa Maria,BR,2020-03-18 19:01:01,-29.68,-53.81,75,74,80.60,3.36

### Humidity Heatmap
* Configure gmaps.
* Use the Lat and Lng as locations and Humidity as the weight.
* Add Heatmap layer to map.

In [16]:
gmaps.configure(api_key=g_key)

In [17]:
# Customize the size of the figure
figure_layout = {
    'width': '500px',
    'height': '400px',
    'border': '1px solid black',
    'padding': '1px',
    'margin': '0 auto 0 auto'
}

locations = df[['Latitude', 'Longitude']]
weights = df['Humidity']
fig = gmaps.figure(layout = figure_layout)

# Add heatmap layer
fig.add_layer(gmaps.heatmap_layer(locations, weights=weights))
fig

Figure(layout=FigureLayout(border='1px solid black', height='400px', margin='0 auto 0 auto', padding='1px', wi…

### Create new DataFrame fitting weather criteria
* Narrow down the cities to fit weather conditions.
* Drop any rows will null values.

In [18]:
new_types_df = pd.DataFrame(df, columns = ["City", "Max Temperature", "Wind Speed", "Cloudiness"])

max_temperature = (new_types_df["Max Temperature"] <= 80) & (new_types_df["Max Temperature"] > 70)
wind_speed = new_types_df["Wind Speed"] < 10
cloudiness = new_types_df["Cloudiness"] == 0

# new_types_df
new_types_df[max_temperature & wind_speed & cloudiness]

          City  Max Temperature  Wind Speed  Cloudiness
35    San Juan            76.78        8.28           0
167     Yulara            77.00        5.82           0
384      Murud            70.12        2.73           0
449   Ngunguru            71.01        3.00           0
476  Mount Isa            77.00        8.05           0
559  Vetapālem            74.26        3.49           0

### Hotel Map
* Store into variable named `hotel_df`.
* Add a "Hotel Name" column to the DataFrame.
* Set parameters to search for hotels with 5000 meters.
* Hit the Google Places API for each city's coordinates.
* Store the first Hotel result into the DataFrame.
* Plot markers on top of the heatmap.

In [19]:
hotel_df = pd.DataFrame(df, columns=["City", "Country", "Latitude", "Longitude"])

hotel_df["Hotel Name"] = ""

hotel_df

              City Country  Latitude  Longitude Hotel Name
0        Busselton      AU    -33.65     115.33
1      Port Alfred      ZA    -33.59      26.89
2    Pacific Grove      US     36.62    -121.92
3           Wanaka      NZ    -44.70     169.15
4        Havøysund      NO     71.00      24.66
..             ...     ...       ...        ...        ...
563      Bāgeshwar      IN     29.85      79.77
564          Galle      LK      6.04      80.22
565          Altay      CN     47.87      88.12
566        Yenagoa      NG      4.92       6.26
567    Santa Maria      BR    -29.68     -53.81

[568 rows x 5 columns]

In [20]:
target_coordinates = f"{hotel_df['Latitude'][0]},{hotel_df['Longitude'][0]}"
target_search = "hotel"
target_radius = 5000
target_type = "hotel"

# set up a parameters dictionary
params = {
    "location": target_coordinates,
    "keyword": target_search,
    "radius": target_radius,
    "type": target_type,
    "key": g_key
}

# base url
base_url = "https://maps.googleapis.com/maps/api/place/nearbysearch/json"

# run a request using our params dictionary
response = requests.get(base_url, params=params)

In [21]:
pprint(response.json(), depth=1)

{'html_attributions': [], 'results': [...], 'status': 'OK'}

In [22]:
hotel_df.iloc[0][0]

'Busselton'

In [23]:
#creates a list to capture hotel names to insert into dataframe
hotel_name = []

# params dictionary to update each iteration
params = {
    "radius": 5000,
    "types": "hotel",
    "keyword": "hotel",
    "key": g_key
}

for index, row in hotel_df.iterrows():
    # get lat, lng from df
    Latitude = row["Latitude"]
    Longitude = row["Longitude"]

    # change location each iteration while leaving original params in place
    params["location"] = f"{Latitude},{Longitude}"

    base_url = "https://maps.googleapis.com/maps/api/place/nearbysearch/json"

    # make request and print url
    name_address = requests.get(base_url, params=params)
    
    # convert to json
    name_address = name_address.json()
    # print(json.dumps(name_address, indent=4, sort_keys=True))
    try:
#         hotel_df.iloc[index, 4] = name_address['results'][0]['name']
        hotel_name.append(name_address['results'][0]['name'])
    except IndexError:
        hotel_name.append(np.nan)

In [24]:
hotel_name

['The Sebel Busselton',
 'The Halyards Hotel',
 'Hotel Pacific',
 'Edgewater Hotel- Lake Wanaka, New Zealand',
 'Havøysund Hotel & Rorbuer',
 nan,
 'Foveaux Hotel',
 'Hostel "Baltiysky Les"',
 'Paradise First Hotel',
 'Hotel Residence KANGABA',
 nan,
 'Pond Country Club',
 nan,
 'Radisson Blu Hotel, Tromsø',
 nan,
 nan,
 'The Explorer Hotel',
 'Hotel Svetlogorsk JBIK',
 'اقامتگاه بومگردی هرموزیا',
 'The Edgewater Resort and Spa',
 'Hospitality Carnarvon',
 'Old Colony Inn',
 'Gostinitsa Galaktika',
 nan,
 'Los Cauquenes Resort & Spa',
 'Falls Hotel',
 'ME Cabo',
 'Hotel Plaza',
 "Pension Maro'i",
 'Distinction Dunedin Hotel',
 'The Marine Hermanus',
 nan,
 'Pestana Bahia Praia',
 'Hotel Da Vila',
 'Chautauqua Harbor Hotel',
 'Del Bono Park Hotel Spa & Casino',
 'Le Meridien Bora Bora',
 'Medhufushi Island Resort',
 nan,
 nan,
 nan,
 nan,
 'Sheraton Kauai Resort at Coconut Beach',
 nan,
 nan,
 'Hotel Buganville Express',
 'Hotel Solymar Galapagos',
 nan,
 nan,
 nan,
 'Hotel Xaguate',
 'Kairos Cottage',
 'Gran Hotel',
 'Mövenpick Hotel Qassim',
 'Premier Hotels & Resorts',
 'Carrefour',
 'Pier Side Landing',
 'Lagoon Palace Hotel Batticaloa',
 'Arktika',
 'Hotel New Amami',
 'Hotel Grand Chancellor Hobart',
 nan,
 'Al Camar Lodge',
 'Hotel Klaksvík',
 '7 Days Inn',
 'Mar Doce De Abrolhos',
 'Laguna Beach Hotel & Spa',
 nan,
 'Pebbles Inn',
 nan,
 'The Kindler Hotel',
 'Grand Naniloa Hotel Hilo - a DoubleTree by Hilton',
 "Pike's Waterfront Lodge",
 'Simplicité Marquises',
 'Orgin Hotel',
 nan,
 'Talnakh Hotel',
 "Usad'ba Sarkel",
 'Hotel Ilha Graciosa',
 'Orlanova Hotel',
 'Les Embruns Du Baril',
 'GRAN HOTEL SAN LUIS GOLD',
 'Anantara Iko Mauritius Resort & Villas',
 'The Prestige Hotel Penang',
 'Maravilha Palace Hotel',
 nan,
 'Hotel Wimpey',
 'Gostinitsa V Salyme',
 'Kashinin Hotel Ethiopia',
 nan,
 nan,
 'The Bay Hotel',
 'Hotel Ella',
 'Alta Patagonia Apart',
 nan,
 'Holiday Inn Express Winnemucca',
 "Manapescale (Chambre d'hôtes)",
 'Inubosaki Kanko Hotel',
 'eSuites Vila do Mar',
 'Mystic Sands',
 nan,
 'Hampton Inn Havelock',
 'Esperance Chalet Village',
 'Hotel Severyanka',
 nan,
 'OYO 1051 De Loran Hotel',
 'Hotel Angmagssalik',
 nan,
 'Hotel Kununurra',
 'Top of the World Hotel',
 'Hotel Terraços da Beira (Trail Abutres)',
 'Complejo Bahia Ballenas',
 'Pickerel Bay Cabins',
 nan,
 nan,
 'Bredasdorp Country Manor',
 'BON Hotel Waterfront Richards Bay',
 'Ocean Centre Hotel',
 'Walkabout Lodge & Tavern',
 nan,
 'The Yarrow Hotel',
 'Baza Otdykha "Dolina Ressy"',
 'Hotel Royal Tocopilla',
 'Zarya',
 'Renqiu Atour Hotel',
 nan,
 "Mary-Ann's Polarrigg",
 'InterContinental Le Moana Bora Bora',
 'Kemping wifi hotel',
 'Casa da Nena Pensión',
 'Shelikof Lodge',
 'Hotel Napoleon',
 'Ankobra Beach Resort',
 'Hampton Inn Fort Smith',
 'Katsuura Hotel Mikazuki',
 nan,
 'Royal Nawab Marriage Hall',
 nan,
 'Hotel Central',
 nan,
 nan,
 'Hotel Fazenda Água Santa',
 'Port Lincoln Hotel',
 'Kak Doma',
 nan,
 nan,
 'Hotel Plaza Lebu',
 'Spirit River Hotel Ltd',
 nan,
 'Adriya',
 'Tourist House - Sablino',
 'Albertine hotel',
 'はる家 ならまち ｜ HARUYA Naramachi',
 'GreenStar Hotel Jyväskylä',
 'ParrotFish Bay',
 'Millbury Guesthouse',
 'HOTEL TIERRA AZUL',
 '7 Days Inn Korla Coach Station Branch',
 'Hotel Icefiord',
 'The Anchorage Hotel',
 'Azul Singular',
 'Hotel Pousada Barra Beach',
 nan,
 'Protea Hotel by Marriott Saldanha Bay',
 nan,
 'Queens Beach Motor Hotel',
 'Qaanaaq Hotel',
 'Sails in the Desert',
 nan,
 'Chateau on the Park - Christchurch, a DoubleTree by Hilton',
 nan,
 nan,
 'Bamboo Bungalow',
 'Four Points by Sheraton Juneau',
 'Bannisters Pavilion',
 'Budget Guesthouse Borgustova',
 'The Jade Emu International Hostel',
 nan,
 'Hotel Marina',
 'おびむらさき',
 'Grand Ibro Hotel',
 "Hunter's B&B",
 'La Quinta Inn by Wyndham Eagle Pass',
 'Hôtel Dolce Notte',
 'Sheraton Mar del Plata Hotel',
 "Gina's Guesthouse - Upernavik",
 nan,
 'Arctic Hotel Nordkapp',
 'Lakeview Hotel Motel',
 'Hotell Frøya',
 nan,
 'Mar Guesthouse',
 'Huilai Hotel',
 'SPOT ON 66011 Hotel Aagaam',
 nan,
 nan,
 'Wyndham Garden Lake Guntersville',
 'Ocean Dunes Resort',
 'THE REDWOOD RIVERWALK HOTEL',
 'Atlantis Hotel',
 'Frobisher Inn',
 'Key-oh Lodge',
 'Royal Plaza Hotel 帝京酒店',
 'Codrington Gardens Bed And Breakfast',
 'DoubleTree by Hilton Hotel San Jose',
 nan,
 'The Deltin',
 'Jay Bhavani Hotel',
 'Otel Fatih',
 nan,
 nan,
 'Hotel Kap Farvel',
 'Nouvata',
 nan,
 'Pousada Pura Vida Club Brasil',
 'Crowne Plaza Alice Springs Lasseters',
 nan,
 'Lakefront Lodge',
 'Hotel Vestmannaeyjar',
 'Pazo de Verdes',
 nan,
 'Canopy by Hilton Minneapolis Mill District',
 'Best Western Danbury/Bethel',
 'Salalah Gardens Hotel',
 'Friendship International Hotel',
 'Courtyard by Marriott Ardmore',
 'Friendship Hotel',
 'A.J.J Palace hotel',
 'HOTEL PLAZA',
 'Hilton Garden Inn Detroit Troy',
 nan,
 'Clarion Collection Hotel Packhuset',
 'Hotel Devon',
 'Агат',
 'Madero Aysen Hotel',
 'Shangri-La Hotel, The Marina, Cairns',
 'Hotel adras',
 'Taloa Heights',
 'Sails Port Macquarie by Rydges',
 nan,
 'Tru By Hilton St. George',
 nan,
 'Manmimar Nature Lodge',
 nan,
 nan,
 'Hotel Kairós',
 'Turtle Nest Inn & Condos',
 'Courtyard by Marriott Orlando Altamonte Springs/Maitland',
 nan,
 'Dreams Acapulco Resort & Spa',
 'Pousada Verdes Mares',
 'Hotel Wemperhardt',
 nan,
 'Hotel Guarapousada',
 'Hilton Garden Inn Sacramento Elk Grove',
 'Altinsaray',
 'Tayga, Gostinitsa',
 'The Ritz-Carlton, Half Moon Bay',
 'Silver House Hotel',
 'Hôtel Les Criquets',
 'Casa Rodo 53',
 nan,
 'Maitai Lapita Village Huahine',
 nan,
 nan,
 nan,
 'Hotel Ritz Lauca',
 'Comfort Inn',
 'Hotel Kanjirowa',
 'Hampton Inn & Suites Del Rio',
 nan,
 nan,
 'Ajdabiya Hotel',
 'Hotel Regency Country Club',
 'Hotel North Pearl',
 'Riverside Inn Resort',
 'Dodge House Hotel & Convention Center',
 'Pousada Raizes',
 'The Huts',
 'iu Hotel Namibe',
 'Golden Tulip Porto Vitória',
 'Hotel Villa Kitzia Huacho',
 'Days Hotel & Suites Ivy Zunyi',
 'Yakutia Hotel',
 'Hotel Viktoria',
 'Khostel "U Kamina"',
 nan,
 'Tibati Hotel',
 'Hilton Garden Inn Lompoc',
 'Vardö Apartments',
 nan,
 'Maui Beach Hotel',
 "d'Ox Ville Hotel",
 'Holiday Inn Express & Suites Malvern',
 'Gostinitsa Alrosa',
 'Lidotel Hotel Boutique San Cristobal',
 nan,
 nan,
 nan,
 'Hotel Ayuana',
 'Naujaaraaluit – Clyde River Hotel',
 'Shanti Maurice Resort & Spa',
 'Jinjiang Inn Jiayuguan Lanxin Road Branch',
 'River Downs Cottage',
 'Red Lion Hotel Coos Bay',
 'Grand Hotel',
 nan,
 nan,
 nan,
 'Pine Lodge Bulolo',
 'Hotel "Favorite"',
 'Casa Rural Aloe Vera',
 'Barn Bed and Breakfast',
 'Hotel "Sunrise"',
 'Hotel Home',
 'GreenTree Inn Hebei DingZhou Railway Station Business Hotel',
 'Kinwica',
 'Drayton Manor Hotel',
 'Hotel Olafsvik',
 nan,
 'Punta Zicatela Hotel',
 'Jalu Hotel',
 nan,
 'TRYP Melilla Puerto Hotel',
 'The Tower House',
 'The Grand Hotel Golf Resort & Spa, Autograph Collection',
 'Hotel Recanto da Praça',
 'Internationnal hotel',
 'Gran Hotel Bahía del Duque Resort',
 'Westmark Fairbanks Hotel & Conference Center',
 'Geopur',
 'Bunia Executive Lodge',
 'Heritage Hotel',
 'فندق المواجيد',
 'Shangri-La Hotel',
 'Namatanai Hotel',
 'Hotel Fessla',
 'HOTEL OASIS',
 nan,
 'Sundog Inn',
 'بورتو بردية',
 'Ridge Royal Hotel, Cape Coast Ghana',
 'Fosshotel Húsavík',
 'Hospedaje la Amistad',
 'Gostevoy Dom Mini Gostinitsa',
 'Hotel Tazovchanka',
 'Taj on Byrnes Mareeba Luxury Accommodation',
 nan,
 'Hilton Garden Inn Dulles North',
 'TDC Village (Hundred Man Camp)',
 'Hotel Pousada dos Sonhos',
 'Lancaster Inn',
 'Quest Hotel San Denpasar',
 'Villa Nestor',
 'Salam Hotel',
 'The Inn at Longshore by OnTheMarc',
 'Hotel First Class',
 'Hotel Hacienda de Abajo',
 'La Quinta Inn & Suites by Wyndham Miami Cutler Bay',
 nan,
 nan,
 nan,
 'Aung Naing Thu Motel',
 'GOTO TSUBAKI HOTEL',
 'Hotel Garapacho',
 'Hotel Fine Shiga Ritto',
 nan,
 'George Hotel',
 'Palacio Estoril Golf & Spa Hotel, Cascais',
 'Posada Real Inn',
 nan,
 'OURE TERA beach resort',
 'Enjoy Coquimbo Hotel de la Bahía',
 'The Streamliner Hotel Apartment',
 'Pensiunea Sophia',
 'Aurora Inn & Suites',
 nan,
 'Mehamn Arctic Hotel AS',
 'Hotel "Orbita"',
 'Best Western Inn Tooele',
 'Shiny River Hotel',
 nan,
 'Mercure Bengkulu',
 'Zig Zag Motel',
 'Golden Swan Beach Resort',
 'Fortune Resort Bay Island',
 "Ron and Tony's Bed & Breakfast",
 'Grand Resort And Spa,Gambella',
 'Gostinitsa Mup Zhkkh',
 nan,
 nan,
 'DoubleTree by Hilton Hotel Anshun',
 'Horizon Inn & Suites',
 'Maritime Inn Port Hawkesbury',
 'Hotel Los Caracoles',
 nan,
 nan,
 'Hotel Villarreal',
 'Holmestrand Hotels',
 'Eastern & Oriental Hotel, Penang',
 'Hotel Nord',
 'Pousada Paço do Lavradio',
 'Dali Hotel',
 'Hotelʹ Turiya',
 'Hotel Mayeye Foutou',
 'DoubleTree by Hilton Hotel Port Huron',
 'La Vista Kushirogawa',
 'JW Marriott Hotel Surabaya',
 nan,
 nan,
 'Franklin Hotel & Motel',
 'Latitude20 Roebourne Village',
 'Lucania Palazzo Hotel',
 nan,
 nan,
 nan,
 nan,
 'Bugaendrus Paradise',
 'Hotel Jardines Baja',
 nan,
 'Grand Isla Navidad Resort',
 'Grand Hotel',
 'Hotel Playa El Cable',
 'La Quinta Inn by Wyndham Abilene',
 'Hotel Villa De Aranda',
 'Paraíso Hotel',
 'Sitka Hotel & Restaurant',
 nan,
 'Gostinitsa "Kak Doma"',
 'Turis Firper Hotel',
 "Marriott's Ko Olina Beach Club",
 'Ossora',
 'Shizunai Eclipse Hotel',
 'ИП Аксёнова С.В.',
 'Binogawan Beach Resort',
 'Hotel Grot',
 'HOTEL TOP',
 'Ulvesund FYR',
 'Song Hotel Sydney',
 'Best Western Plus Inn of Hayward',
 'Hotelli Ravintola Kasari',
 'Liamo Reef Resort - Kimbe International Hotel',
 'Zamkovyj Park-Hotel',
 'Damal Hotel',
 'Villa Habsburg',
 nan,
 'Pousada do Cabeça',
 'Best Western Thompson Hotel & Suites',
 'Panamericana Hotel Ancud',
 'Quality Hotel Oceans Tutukaka',
 'El Salam Hotel',
 'Hotel Sofitel Legend Old Cataract Aswan',
 nan,
 'Hotel Guantánamo',
 'Hotel Veredas do Araguaia',
 'Hyatt Regency Perth',
 'Hotel Sisimiut',
 nan,
 'Sofitel Xining',
 'Zilwa Attitude Hotel',
 'Oceanaire Resort Hotel',
 'Hotel Liburna',
 'Bays Garden Hotel',
 'Al Madina Hotel & Restaurant',
 'Hanting Hotel',
 'Lakeview Gimli Resort',
 'Country Inn & Suites by Radisson, Marinette, WI',
 'Hotel Sagua',
 'Protea Hotel by Marriott Takoradi Select',
 'Fairfield by Marriott Bintulu Paragon',
 nan,
 '哈尔滨万达索菲特大酒店',
 'El Sosiego',
 'Ungoofaaru Inn',
 'Avinurme Hostel',
 'Odar kanawal',
 'Abacus Motel',
 nan,
 'Paradise Bay Resort',
 'Palace Hotel',
 'The Whisky Vaults Hotel',
 'E-Hotel Muravlenko',
 'Hôtel Oasis Bouna',
 'Nii Dentis Hotel',
 'Cassowary Hotel',
 'Victoria Village',
 'Juman Hotel',
 nan,
 'Marriott Santa Cruz de la Sierra Hotel',
 'Hattusa Vacation Thermal Club Erzin',
 'Posseidon Hotel',
 'Bay House',
 nan,
 'Hotel Mathilda',
 'MH Peniche',
 'Dongying Blue Horizon Xinyue Hotel',
 'Villa Ballstad',
 'Gostinitsa Intera',
 'Hotel Olako',
 'VIP Executive Azores Hotel',
 'Hotel Cabildo',
 'Guest House on Kooperativnaya',
 'The Freeport Inn and Marina',
 nan,
 "Paddy D'sawah Guest house",
 nan,
 'Hôtel Riad Asfi',
 'Welcome Hotel Meschede/Hennesee',
 'BISMI HOTEL',
 'Hotel Meuligoe',
 'Hotel Memory',
 'HOTEL R. SOARES',
 'Companion',
 nan,
 'Hotel Colonial',
 'Hotel Perdana Kota Bharu, Kelantan.',
 nan,
 nan,
 'ROYAL STAR GUEST HOUSE',
 'Vishwa Geeta Bhawan',
 'Milk Factory',
 'Sandaun Surf Hotel',
 'Swiss-Belinn Hotel Luwuk',
 nan,
 'Afra Hotel (Alascalh)',
 'Hotel Navegadores',
 'Diamante Hotel',
 'Niyama Private Islands Maldives',
 'Central Hotel',
 nan,
 'Hampton Inn Houma',
 'Chanthra Hotel',
 'The Mill Casino • Hotel & RV Park',
 'Campsite Orlan',
 'Casa Nemo Beach Resort & Spa',
 'SpringHill Suites by Marriott Thatcher',
 'Wulingcheng Hotel',
 'Hotel Puerto Colombia',
 nan,
 'Nayra Palace Hotel',
 nan,
 'Castelo Encantado',
 'Clubhouse Hotel & Suites',
 'Sheraton Lima Hotel & Convention Center',
 'Hôtel Opémiska',
 'Silver Point Villa Hotel',
 'Best Western Plus Bayshore Inn',
 'Tsimus',
 'Hotel Indigo Mount Pleasant',
 'The Bayside Bed and Breakfast',
 'Quality Inn & Suites Lehigh Acres Fort Myers',
 'Hotel Contessa',
 'Hotel Nemuro Kaiyoutei',
 'Bababa Guest Inn',
 nan,
 'Hotel Borba Palace',
 'Kenai River Lodge',
 'Casa Andina Standard Talara',
 'Art Hotel on York',
 'AMARAVATHI GRAND',
 'Hotel Marilsa',
 'Hotel Faleza Rozewie',
 nan,
 'KMVN TRH Bageshwar',
 'Amari Galle Sri Lanka',
 'Yinlu Hotel',
 'De Brass Suites',
 'Hotel Appel']

In [25]:
# NOTE: Do not change any of the code in this cell

# Using the template add the hotel marks to the heatmap
info_box_template = """
<dl>
<dt>Name</dt><dd>{Hotel Name}</dd>
<dt>City</dt><dd>{City}</dd>
<dt>Country</dt><dd>{Country}</dd>
</dl>
"""
# Store the DataFrame Row
# NOTE: be sure to update with your DataFrame name
hotel_info = [info_box_template.format(**row) for index, row in hotel_df.iterrows()]
locations = df[["Latitude", "Longitude"]]

In [26]:
# Add marker layer ontop of heat map

markers = gmaps.marker_layer(locations)
fig.add_layer(markers)
fig

# Display Map

Figure(layout=FigureLayout(border='1px solid black', height='400px', margin='0 auto 0 auto', padding='1px', wi…